#pragma config(Motor,  port1,           rightDriveA,   tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightDriveB,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftDriveA,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftDriveB,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           launchA,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           launchB,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           launchC,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           launchD,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           feedMe,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          seymore,       tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(UART_Usage, UART2, uartVEXLCD, baudRate19200, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int value;
bool driveMode;
int actrpm = 5; //this will be the actual rpm -uses test value
string rpma;
string rpmb;
string rpmc;
string rpmd;
int lastBtnPressed;
int menuValue;
int actMotPowaah = 22; //this will be the actual powaah -uses test value
string motPowaaha;
string motPowaahb;
string mainBattery;
bool backlight = false;
const short waittime = 150;
//hi Yerffej this is Nayr

//=================================================================================================

void launch(int speed)
{
	motor(launchA) =  speed;
	motor(launchB) =  speed;
	motor(launchC) =  speed;
	motor(launchD) =  speed;
	value = speed;
}
//=================================================================================================
void drive()
{
	 //sets drive mode
 	if(vexRT[Btn7R] == 1 & driveMode == false)
	{
		driveMode = true;
	}
	if(vexRT[Btn7R] == 1 & driveMode == true)
	{
		driveMode = false;
	}
  //drive mode 1
	if(driveMode == true)
	{
		motor(rightDriveA) = vexRT[Ch2];
		motor(rightDriveB) = vexRT[Ch2];
		motor(leftDriveA) = vexRT[Ch3];
		motor(leftDriveB) = vexRT[Ch3];
	}
	//drive mode 2
	if(driveMode == false)
	{
		motor(rightDriveA) = -vexRT[Ch3];
		motor(rightDriveB) = -vexRT[Ch3];
		motor(leftDriveA) = -vexRT[Ch2];
		motor(leftDriveB) = -vexRT[Ch2];
	}
}
//=================================================================================================

void feed(int num)
{
	motor(feedMe) = num;
	motor(seymore) = num;
}
//=================================================================================================

void menuValues()
{
	lastBtnPressed = nLCDButtons;
	if(lastBtnPressed == 1)
	{
		--menuValue;
	}
	if(lastBtnPressed == 4)
	{
		++menuValue;
	}
	if(lastBtnPressed == 2)
	{
		menuValue = 0;
	}
	if(menuValue > 1)
	{
		menuValue = 1;
	}
	if (menuValue < -2)
	{
		menuValue = -2;
	}
	if (nLCDButtons == 7 && backlight == true)
	{
		backlight = false;
		bLCDBacklight = false;
		wait1Msec(200);
	}
	if (nLCDButtons == 7 && backlight == false)
	{
		backlight = true;
		bLCDBacklight = true;
		wait1Msec(200);
	}
}
//=================================================================================================

void rampUp()
{
	motor(launchA) =  45;
	motor(launchB) =  45;
	motor(launchC) =  45;
	motor(launchD) =  45;
}
//=================================================================================================

task display()
{
	menuValue = 0; //Starting value
	bLCDBacklight = false;
	while(true)
	{
		//Display correct screen
	while(menuValue == 0)
	{
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "BangBang Code");
		displayLCDCenteredString(1, "-Tynan and Jeff-");
		menuValues();
		wait1Msec(waittime);
		EndTimeSlice();
	}
	while(menuValue == 1)
	{
		string motPowaaha = "MotPowaah: ";
		string motPowaahb = actMotPowaah;
		strcat(motPowaaha, motPowaahb);
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, motPowaaha);
		//displayLCDCenteredString(1, lMotPowaah);
		menuValues();
		wait1Msec(waittime);
		EndTimeSlice();
	}
	while(menuValue == -1)
	{
		string rpma = "RPM: ";
		string rpmb = actrpm;
		strcat(rpma, rpmb);
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, rpma);
		//displayLCDCenteredString(1, lrpm);
		menuValues();
		wait1Msec(waittime);
		EndTimeSlice();
	}
	while(menuValue == -2)
	{
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "Battery Voltage:");
		displayLCDString(1, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);
		menuValues();
		wait1Msec(waittime);
		EndTimeSlice();
	}
	while(menuValue < -2 || menuValue > 1)
	{
		menuValues();
		EndTimeSlice();
	}
	}
}
//=================================================================================================

task main()
{
	startTask(display); //starts the display task
	menuValue = 0; //Starting value
	bLCDBacklight = false;
	driveMode = true;
	while(true)
	{


  if(vexRT[Btn7D] == 1)
  {
  	rampUp();
  }

	if(vexRT[Btn5U] == 1)
  {
  	launch(80);
  }
  if(vexRT[Btn5D] == 1)
  {
  	launch(0);
  }
  if(vexRT[Btn8U] == 1)
  {
  	launch(127);
  }
  if(vexRT[Btn8R] == 1)
  {
  	launch(100);
  }
  if(vexRT[Btn8L] == 1)
  {
  	launch(70);
  }
  if(vexRT[Btn8D] == 1)
  {
  	launch(60);
  }

  if(vexRT[Btn6U] == 1)
  {
  	feed(127);
  }
  else if(vexRT[Btn6D] == 1)
  {
  	feed(-127);
  }
  else
  {
  	feed(0);
  }

  if(vexRT(Btn7U)==1)
   {
     value = value+1;
     launch(value);
   }
   if(vexRT(Btn7L)==1)
   {
     value = value-1;
     launch(value);
   }
   EndTimeSlice();

}

}
