#pragma config(Sensor, dgtl1,  launchEncoder,  sensorQuadEncoder)
#pragma config(Motor,  port1,           rightDrive,    tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveRight)
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightDriveB,   tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           leftDriveB,    tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           feedA,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           feedB,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           launchA,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           launchB,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           launchC,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          launchD,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

byte motorSpeed;
int tickInitial, tickFinal, tickDifference;
float RPMs;
int target;

void usual()
	{
	//drive code
	motor(rightDrive) = vexRT[Ch2];
	motor(rightDriveB) = vexRT[Ch2];
	motor(leftDrive) = vexRT[Ch3];
	motor(leftDriveB) = vexRT[Ch3];

	//feed code
  if(vexRT(Btn6U)==1)
	{
		motor(feedA) = 127;
		motor(feedB) = 127;
	}
	else if(vexRT(Btn6D)==1)
	{
		motor(feedA) = -127;
		motor(feedB) = -127;
	}
	else
	{
		motor(feedA) = 0;
		motor(feedB) = 0;
	}
	}

	void launch()
	{
		motor(launchA) = motorSpeed;
		motor(launchB) = motorSpeed;
		motor(launchC) = motorSpeed;
		motor(launchD) = motorSpeed;
	}

task main()
{
	while(1==1)
{
	usual();
	//sets flywheel RPM to the desired value
	tickInitial = SensorValue(launchEncoder);
	wait1Msec(5);
	tickFinal = SensorValue(launchEncoder);
	tickDifference = tickInitial - tickFinal;
	RPMs = tickDifference/360*12000;

	if(RPMs < target)
	{
		motorSpeed = motorSpeed + 1;
	}
	else if(RPMs > target)
	{
		motorSpeed = motorSpeed - 1;
	}
	else
	{
		motorSpeed = motorSpeed + 0;
	}
	if(motorSpeed < 0)
	{
		motorSpeed = 0;
	}
	//actual launch code
	launch();
		if (vexRT(Btn5U)==1)
		{
			target=1100;
		}
		if (vexRT(Btn7U)==1)
		{
			target=1000;
		}
		if (vexRT(Btn7L)==1)
		{
			target=950;
		}
		if (vexRT(Btn7D)==1)
		{
			target=900;
		}
		if (vexRT(Btn7R)==1)
		{
			target=800;
		}
		if (vexRT(Btn5D)==1)
		{
			motorSpeed = 0;
		}
}
}
